filters:
  allowlist:
    allow:
      - '/\[\^.+\]: +[「『（]/'

rules:
  preset-ja-technical-writing:
    sentence-length:
      max: 140
    max-comma: false
    max-ten: false
    max-kanji-continuous-len:
      max: 7
      allow: []
    arabic-kanji-numbers: false
    no-mix-dearu-desumasu: false
    ja-no-mixed-period: false
    no-double-negative-ja: true
    no-dropping-the-ra: true
    no-doubled-conjunctive-particle-ga: true
    no-doubled-conjunction: true
    no-doubled-joshi:
      min_interval: 1
      allow: ["も", "や", "たり"]
    no-nfd: true
    no-exclamation-question-mark: false
    no-hankaku-kana: true
    ja-no-weak-phrase: false
    ja-no-successive-word: true
    ja-no-abusage: true
    ja-no-redundant-expression: true

  preset-jtf-style:
    1.1.1.本文: false
    1.1.2.見出し: false
    1.1.3.箇条書き: false
    2.1.6.カタカナの長音: true
    2.2.2.算用数字と漢数字の使い分け: false
    3.1.1.全角文字と半角文字の間: false
    3.1.2.全角文字どうし: false
    4.3.1.丸かっこ（）: false

  terminology:
    defaultTerms: false
    skip: ["Blockquote"]
    terms: lint-config/terms.json

  "@textlint-ja/textlint-rule-no-insert-dropping-sa": true
  ja-hiragana-hojodoushi: true
